name: directus_core
description: The unofficial SDK for Directus with REST API and auth. This core package does not require Flutter. Extended by RLO
version: 0.12.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Http client
  dio: ">=5.0.0 <6.0.0"
  # Annotations
  meta: ^1.9.1
  # Used for decorators for JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.9
  mockito: ^5.4.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  lints: ^3.0.0
