name: directus
description: The unofficial SDK for Directus, provides REST API and authentication. Requires Flutter. Extended with Tokens
version: 0.12.2
homepage: https://www.directus.io
repository: https://github.com/apstanisic/directus-dart
issue_tracker: https://github.com/apstanisic/directus-dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  directus_core: 0.12.0
  # Storage
  shared_preferences: ^2.2.2
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
